# Generated by Django 5.0.3 on 2024-05-31 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profesores', '0002_post_remove_matricula_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
