# Generated by Django 5.0.4 on 2024-06-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profesores', '0003_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesores'},
        ),
    ]
