# Generated by Django 5.0.3 on 2024-05-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
