# Generated by Django 5.0.3 on 2024-05-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_articulos_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='score',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='text',
        ),
    ]
