# Generated by Django 5.0.4 on 2024-06-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknow', max_length=50)),
                ('description', models.TextField(default='Vacio')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='unknow', max_length=50)),
                ('last_name', models.CharField(default='unknow', max_length=50)),
                ('birth_date', models.DateField(default='2024-07-01')),
                ('enrollment_date', models.DateField(default='2024-07-01')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='unknow', max_length=50)),
                ('last_name', models.CharField(default='unknow', max_length=50)),
                ('hire_date', models.DateField(default='2024-07-01')),
                ('specialization', models.CharField(default='unknow', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknow', max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='gestion.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default='2024-07-01')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.curso')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, default=' ', max_length=2, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.curso')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.profesor'),
        ),
    ]
