# Generated by Django 5.0.4 on 2024-09-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula_materia',
            old_name='nombre',
            new_name='nombre_matricula_materia',
        ),
        migrations.RenameField(
            model_name='tipo_evaluacion',
            old_name='nombre',
            new_name='nombre_tipo_evaluacion',
        ),
    ]
