# Generated by Django 5.0.4 on 2024-06-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['name'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['name'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('can_view_grades', 'Puede ver sus calificaciones'), ('can_edit_profile', 'Puede editar su perfil')], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['student', 'course'], 'verbose_name': 'Matricula', 'verbose_name_plural': 'Matriculas'},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['student', 'course'], 'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='address',
            field=models.CharField(default='desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='phone',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='first_name',
            field=models.CharField(default='desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='last_name',
            field=models.CharField(default='desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='first_name',
            field=models.CharField(default='desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='last_name',
            field=models.CharField(default='desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='specialization',
            field=models.CharField(default='desconocido', max_length=100),
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='estudiante',
        ),
    ]
