# Generated by Django 5.0.4 on 2024-06-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_asignatura_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='secretario', max_length=50)),
                ('last_name', models.CharField(default='apellido_secretario_opcional', max_length=50)),
                ('birth_date', models.DateField(default='2024-07-01')),
                ('email', models.EmailField(default='email', max_length=254)),
                ('phone', models.CharField(default='0', max_length=50)),
                ('address', models.CharField(default='desconocido', max_length=50)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('add_student', 'Puede agregar estudiante'), ('change_student', 'Puede cambiar estudiante'), ('delete_student', 'Puede eliminar estudiante'), ('view_student', 'Puede ver estudiante')],
            },
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('can_edit_grades', 'Puede ver sus calificaciones'), ('can_edit_profile', 'Puede editar su perfil'), ('can_view_profile', 'Puede ver su perfil')], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelTable(
            name='profesor',
            table='profesor',
        ),
    ]
