# Generated by Django 5.0.4 on 2024-07-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_profile_options_rename_id_user_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id_teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id_subject',
        ),
        migrations.AlterField(
            model_name='person',
            name='ci',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
