# Generated by Django 5.0.4 on 2024-10-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_usuario_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_evaluacion',
            options={'ordering': ['id_tipo_evaluacion', 'nombre_tipo_evaluacion'], 'verbose_name': 'Tipo de Evaluacion', 'verbose_name_plural': 'Tipos de Evaluaciones'},
        ),
        migrations.AlterModelTable(
            name='tipo_evaluacion',
            table='tipo_evaluacion',
        ),
    ]
