# Generated by Django 5.0.4 on 2024-06-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_secretario_alter_profesor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretario',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Secretario', 'verbose_name_plural': 'Secretarios'},
        ),
        migrations.AlterModelTable(
            name='secretario',
            table=None,
        ),
    ]
