# Generated by Django 5.0.4 on 2024-06-24 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_secretario_options_alter_secretario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('can_edit_grades', 'Puede ver sus calificaciones'), ('can_edit_profile', 'Puede editar su perfil'), ('can_view_profile', 'Puede ver su perfil'), ('can_view_grades', 'Puede ver las calificaciones de los estudiantes')], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.RemoveField(
            model_name='nota',
            name='course',
        ),
        migrations.AddField(
            model_name='nota',
            name='date_recorded',
            field=models.DateField(default='2024-07-01', verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='nota',
            name='subject',
            field=models.CharField(default='asignatura', max_length=100, verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='gestion.estudiante'),
        ),
    ]
