# Generated by Django 5.0.4 on 2024-07-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_grades_options_alter_period_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
