# Generated by Django 5.0.4 on 2024-06-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_nota_options_alter_profesor_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nota',
            new_name='Grade',
        ),
    ]
