# Generated by Django 5.0.4 on 2024-10-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_metodologia_options_alter_metodologia_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='estado',
            field=models.CharField(default='Inactivo', max_length=25),
        ),
    ]
