# Generated by Django 5.0.4 on 2024-07-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_student_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['id_period', 'name_period', 'year_period'], 'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='id_schedule',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_subject',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
