# Generated by Django 5.0.4 on 2024-10-18 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_materia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=25)),
                ('hora_inicio', models.DateField()),
                ('hora_fin', models.DateField()),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
