# Generated by Django 5.0.4 on 2024-06-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_rename_nota_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Student',
        ),
    ]
