# Generated by Django 5.0.4 on 2024-06-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_rename_estudiante_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('can_edit_grades', 'Puede editar calificaciones'), ('can_edit_profile', 'Puede editar su perfil'), ('can_view_profile', 'Puede ver su perfil'), ('can_view_grades', 'Puede ver las calificaciones de los estudiantes')], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='description',
            field=models.TextField(default='vacio'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='gestion.student'),
        ),
    ]
