# Generated by Django 5.0.4 on 2024-10-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['id_horario'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterModelTable(
            name='horario',
            table='horario',
        ),
    ]
