# Generated by Django 5.0.4 on 2024-06-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_profesor_options_alter_curso_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id_academicPeriod', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_academicPeriod', models.CharField(max_length=50)),
                ('year_academicPeriod', models.DateTimeField(auto_now_add=True)),
                ('semester_academicPeriod', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Periodo Academico',
                'verbose_name_plural': 'Periodos Academicos',
                'db_table': 'academicperiod',
                'ordering': ['id_academicPeriod', 'year_academicPeriod'],
            },
        ),
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id_carrer', models.BigAutoField(default=2, primary_key=True, serialize=False)),
                ('name_carrer', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'carrer',
                'ordering': ['id_carrer', 'name_carrer'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_description', models.TextField()),
                ('id_carrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.carrer')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'course',
                'ordering': ['id_course', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id_grades', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(default='')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('id_curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.course')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'person',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id_registration', models.BigAutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'db_table': 'registration',
                'ordering': ['id_registration', 'id_student', 'id_subject'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_academicPeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.academicperiod')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'subject',
                'ordering': ['id_subject', 'id_teacher'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_teacher', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=50)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.person')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'teacher',
                'ordering': ['id_teacher', 'id_person'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('pass_hash', models.CharField(max_length=50)),
                ('salt', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('EST', 'Estudiante'), ('PRO', 'Profesor'), ('ADM', 'Administrativo')], default='EST', max_length=3)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.person')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'user',
                'ordering': ['id_user', 'id_person'],
            },
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='course',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='student',
        ),
        migrations.DeleteModel(
            name='Secretario',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id_student', 'id_person'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='id_student',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AddField(
            model_name='student',
            name='id_carrer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion.carrer'),
        ),
        migrations.AddField(
            model_name='grades',
            name='id_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestion.person'),
        ),
        migrations.AddField(
            model_name='registration',
            name='id_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.student'),
        ),
        migrations.AddField(
            model_name='registration',
            name='id_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.carrer'),
        ),
        migrations.AddField(
            model_name='grades',
            name='id_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='id_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='id_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.teacher'),
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
