# Generated by Django 5.0.4 on 2024-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_grades_evaluation_type_alter_grades_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='note',
            field=models.IntegerField(choices=[('U', 'Uno'), ('D', 'Dos'), ('T', 'Tres'), ('C', 'Cuatro'), ('CI', 'Cinco')], default=None),
        ),
    ]
