# Generated by Django 5.0.4 on 2024-10-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_horario_options_alter_horario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='anio',
            field=models.IntegerField(default=2020),
        ),
    ]
