# Generated by Django 5.0.4 on 2024-06-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_academicperiod_carrer_course_grades_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pass_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
