# Generated by Django 5.0.4 on 2024-07-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_grades_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='note',
            field=models.IntegerField(blank=True, choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco')], default=None, null=True),
        ),
    ]
