# Generated by Django 5.0.4 on 2024-06-28 18:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_remove_user_pass_hash_remove_user_salt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id_subject'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='id_teacher',
        ),
        migrations.AddField(
            model_name='carrer',
            name='duracion',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='day',
            field=models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], default='LUN', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_subject',
            field=models.CharField(default='Nombre de la materia', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='time_end',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='subject',
            name='time_start',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='id_subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.subject'),
        ),
        migrations.AlterField(
            model_name='carrer',
            name='faculty',
            field=models.CharField(default='Nombre de la facultad', max_length=50),
        ),
        migrations.AlterField(
            model_name='carrer',
            name='id_carrer',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carrer',
            name='name_carrer',
            field=models.CharField(default='Nombre de la carrera', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_person',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_carrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.carrer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.person'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_student',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
