# Generated by Django 5.0.4 on 2024-06-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_remove_user_pass_hash_remove_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
