# Generated by Django 5.0.4 on 2024-08-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_grades_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='behaviour',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
