# Generated by Django 5.0.4 on 2024-11-08 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_horario_hora_fin_alter_horario_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='date',
        ),
    ]
