# Generated by Django 5.0.4 on 2024-09-01 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_student_behaviour_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('detalles', models.CharField(max_length=150)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metodologia',
            fields=[
                ('id_metodologia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_evaluacion',
            fields=[
                ('id_tipo_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='id_career',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_career',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='id_course',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='id_course',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='id_student',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='id_subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='id_period',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='id_student',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='id_subject',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='id_subject',
        ),
        migrations.CreateModel(
            name='matricula_materia',
            fields=[
                ('id_matri_mater', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materia')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evaluacion', models.CharField(max_length=100)),
                ('total_puntos', models.IntegerField(default=100)),
                ('puntos_logrados', models.FloatField(default=0)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_matricula_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.matricula_materia')),
                ('id_metodologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.metodologia')),
                ('id_tipo_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tipo_evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.rol')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario'),
        ),
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
