# Generated by Django 5.0.4 on 2024-11-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_remove_horario_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='date',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='lunes', max_length=10),
        ),
    ]
