# Generated by Django 5.0.4 on 2024-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_person',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
