# Generated by Django 5.0.4 on 2024-11-22 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_horario_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='puntos_logrados',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='id_materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='anio',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='materia',
            name='estado',
            field=models.CharField(choices=[('inactivo', 'Inactivo'), ('activo', 'Activo'), ('finalizado', 'Finalizado')], default='inactivo', max_length=25),
        ),
        migrations.CreateModel(
            name='materia_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=2000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
