# Generated by Django 5.0.4 on 2024-12-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_horario_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('termminado', 'Terminado')], default='inactivo', max_length=25),
        ),
    ]
