# Generated by Django 5.0.4 on 2024-06-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_person_id_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_carrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.carrer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.person'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
