# Generated by Django 5.0.4 on 2024-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_student_id_carrer_alter_student_id_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrer',
            name='id_carrer',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_student',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
