# Generated by Django 5.0.4 on 2024-06-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_carrer_id_carrer_alter_student_id_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name_subject',
            field=models.CharField(default='Ingrese el nombre de la materia', max_length=50),
        ),
        migrations.AlterField(
            model_name='carrer',
            name='faculty',
            field=models.CharField(default='Ingrese el nombre de la facultad', max_length=50),
        ),
        migrations.AlterField(
            model_name='carrer',
            name='name_carrer',
            field=models.CharField(default='ingese el nombre de la carrera', max_length=50),
        ),
    ]
