# Generated by Django 5.0.4 on 2024-06-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_subject_name_subject_alter_carrer_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrer',
            name='duracion',
            field=models.CharField(default='Ingrese la duracion', max_length=50),
        ),
    ]
