# Generated by Django 5.0.4 on 2024-06-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_carrer_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrer',
            name='duracion',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
