# Generated by Django 5.0.4 on 2024-06-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_carrer_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrer',
            name='faculty',
            field=models.CharField(default='Nombre de la facultad', max_length=50),
        ),
        migrations.AlterField(
            model_name='carrer',
            name='id_carrer',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carrer',
            name='name_carrer',
            field=models.CharField(default='Nombre de la carrera', max_length=50),
        ),
    ]
