# Generated by Django 5.0.4 on 2024-06-27 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alter_carrer_faculty_alter_carrer_id_carrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='id_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_subject',
            field=models.CharField(default='Nombre de la materia', max_length=50),
        ),
    ]
