# Generated by Django 5.0.4 on 2024-06-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_teacher_id_subject_alter_subject_name_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.subject'),
        ),
    ]
