# Generated by Django 5.0.4 on 2024-06-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_alter_teacher_id_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id_subject',
        ),
    ]
