# Generated by Django 5.0.4 on 2024-06-07 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_remove_materia_descripcion_horario_aula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='metodo_evaluacion',
            field=models.CharField(choices=[('Oral', 'Oral'), ('Escrito teórico', 'Escrito teórico'), ('Práctico', 'Práctico'), ('Teórico-Práctico', 'Teórico-Práctico')], default='Oral', max_length=20, verbose_name='Método de evaluación'),
        ),
        migrations.AddField(
            model_name='materia',
            name='metodologia',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Metodología'),
            preserve_default=False,
        ),
    ]
